name: Tesing workflow

on: [push]

jobs:
  style-check:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: "Install style checker"
        run: pip install black
      - name: "Run style check"
        run: black --check .

